baseURL: 'https://kuchida1981.github.io/'
languageCode: 'ja-JP'
title: 'U-REI.com'
theme: papermod
copyright: Â© 2023 Kosuke Uchida
publishDir: docs
canonifyURLs: true

Params:
  author: Kosuke Uchida
  description: Sandbox
  DateFormat: 2006-01-02 15:04
  defaultTheme: auto
  hideSummary: false
  ShowBreadCrumbs: true

  profileMode:
    enabled: true
    subtitle: Freelance Software Engineer / Full Stack Developer
    imageUrl: profile.png
    imageTitle: profile

menu:
  main:
    - identifier: about
      name: About
      url: /about/
      weight: 1
    - identifier: services
      name: Services
      url: /services/
      weight: 2
    - identifier: works
      name: Works
      url: /works/
      weight: 3
    - identifier: posts
      name: Posts
      url: /posts/
      weight: 4
    - identifier: archives
      name: Archives
      url: /archives/
      weight: 5
